blank_issues_enabled: false
contact_links:
  - name: Discussion / question
    url: https://github.com/mayurrawte/teamsly/discussions
    about: For questions or general discussion that aren't bug reports or feature requests
